export const UPDATE_SESSION_PROGRESS = 'UPDATE_SESSION_PROGRESS';
export const SET_RANKING_NAME = 'SET_RANKING_NAME';
export const ADD_MEMBER = 'ADD_MEMBER';
export const ADD_SCORE = 'ADD_SCORE';
export const SET_NEXT_RATER = 'SET_NEXT_RATER';
export const SET_NEXT_TARGET = 'SET_NEXT_TARGET';
export const ADD_RATED_TARGET = 'ADD_RATED_TARGET';
